Implement haptic feedback functionality and update ShowFAQs UI
- Introduced a new method in CipherUtils for performing haptic feedback.
- Updated Canvas to store a reference to system UI for haptic feedback.
- Added new drawable resources and layout for the about dialog.
- Updated localization manager to prevent java.lang.NoSuchMethodError cause by the new update.
- Added ```SKY_BUILD_ACCESS_KEY``` in Sky BuildConfig.java required during runtime and taken from the original APK.
- Updated the UI of the credits dialog.
- This version does not work with beta (maybe due to the beta restrictions).